spring:
  datasource:
    url: "jdbc:postgresql://inferno-postgresql-server:5432/inferno"
    username: sa
    password: 12345
  flyway:
    table: "migrations"
    locations: "classpath:database_migrations"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true