create table authors (id bigint generated by default as identity, full_name varchar(255) not null, book_id bigint not null, primary key (id));
create table books (id bigint generated by default as identity, version bigint, title varchar(255) not null, primary key (id));
alter table authors add constraint authors_book_id_fkey foreign key (book_id) references books;